# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheMarvels' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheMarvels
  pod 'MarvelService', :git => 'https://github.com/netomouraa/MarvelService', :tag => '0.1.7'
#  pod 'MarvelService', :path => '/Users/netomoura/Desktop/MarvelService'
  
  target 'TheMarvelsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheMarvelsUITests' do
    # Pods for testing
  end

end
